// Curated list of ~200 major US cities for autocomplete
export const US_CITIES = [
  "New York, NY", "Los Angeles, CA", "Chicago, IL", "Houston, TX", "Phoenix, AZ",
  "Philadelphia, PA", "San Antonio, TX", "San Diego, CA", "Dallas, TX", "San Jose, CA",
  "Austin, TX", "Jacksonville, FL", "Fort Worth, TX", "Columbus, OH", "Charlotte, NC",
  "Indianapolis, IN", "San Francisco, CA", "Seattle, WA", "Denver, CO", "Nashville, TN",
  "Washington, DC", "Oklahoma City, OK", "El Paso, TX", "Boston, MA", "Portland, OR",
  "Las Vegas, NV", "Memphis, TN", "Louisville, KY", "Baltimore, MD", "Milwaukee, WI",
  "Albuquerque, NM", "Tucson, AZ", "Fresno, CA", "Mesa, AZ", "Sacramento, CA",
  "Atlanta, GA", "Kansas City, MO", "Colorado Springs, CO", "Omaha, NE", "Raleigh, NC",
  "Long Beach, CA", "Virginia Beach, VA", "Miami, FL", "Oakland, CA", "Minneapolis, MN",
  "Tulsa, OK", "Tampa, FL", "Arlington, TX", "New Orleans, LA", "Wichita, KS",
  "Cleveland, OH", "Bakersfield, CA", "Aurora, CO", "Anaheim, CA", "Honolulu, HI",
  "Santa Ana, CA", "Riverside, CA", "Corpus Christi, TX", "Lexington, KY", "Stockton, CA",
  "St. Louis, MO", "Saint Paul, MN", "Henderson, NV", "Pittsburgh, PA", "Cincinnati, OH",
  "Anchorage, AK", "Greensboro, NC", "Plano, TX", "Lincoln, NE", "Orlando, FL",
  "Irvine, CA", "Newark, NJ", "Durham, NC", "Chula Vista, CA", "Toledo, OH",
  "Fort Wayne, IN", "St. Petersburg, FL", "Laredo, TX", "Jersey City, NJ", "Chandler, AZ",
  "Madison, WI", "Lubbock, TX", "Scottsdale, AZ", "Reno, NV", "Buffalo, NY",
  "Gilbert, AZ", "Glendale, AZ", "North Las Vegas, NV", "Winston-Salem, NC", "Chesapeake, VA",
  "Norfolk, VA", "Fremont, CA", "Garland, TX", "Irving, TX", "Hialeah, FL",
  "Richmond, VA", "Boise, ID", "Spokane, WA", "Baton Rouge, LA", "Tacoma, WA",
  "San Bernardino, CA", "Modesto, CA", "Fontana, CA", "Des Moines, IA", "Moreno Valley, CA",
  "Santa Clarita, CA", "Fayetteville, NC", "Birmingham, AL", "Oxnard, CA", "Rochester, NY",
  "Port St. Lucie, FL", "Grand Rapids, MI", "Huntsville, AL", "Salt Lake City, UT", "Frisco, TX",
  "Yonkers, NY", "Amarillo, TX", "Glendale, CA", "Huntington Beach, CA", "McKinney, TX",
  "Montgomery, AL", "Augusta, GA", "Aurora, IL", "Akron, OH", "Little Rock, AR",
  "Tempe, AZ", "Columbus, GA", "Overland Park, KS", "Grand Prairie, TX", "Tallahassee, FL",
  "Cape Coral, FL", "Mobile, AL", "Knoxville, TN", "Shreveport, LA", "Worcester, MA",
  "Ontario, CA", "Sioux Falls, SD", "Chattanooga, TN", "Brownsville, TX", "Fort Lauderdale, FL",
  "Providence, RI", "Newport News, VA", "Rancho Cucamonga, CA", "Santa Rosa, CA", "Peoria, AZ",
  "Oceanside, CA", "Elk Grove, CA", "Salem, OR", "Pembroke Pines, FL", "Eugene, OR",
  "Garden Grove, CA", "Cary, NC", "Fort Collins, CO", "Corona, CA", "Springfield, MO",
  "Jackson, MS", "Alexandria, VA", "Hayward, CA", "Lancaster, CA", "Salinas, CA",
  "Palmdale, CA", "Hollywood, FL", "Springfield, MA", "Macon, GA", "Kansas City, KS",
  "Sunnyvale, CA", "Pomona, CA", "Killeen, TX", "Escondido, CA", "Pasadena, TX",
  "Naperville, IL", "Bellevue, WA", "Joliet, IL", "Murfreesboro, TN", "Midland, TX",
  "Rockford, IL", "Paterson, NJ", "Savannah, GA", "Bridgeport, CT", "Torrance, CA",
  "McAllen, TX", "Syracuse, NY", "Surprise, AZ", "Denton, TX", "Roseville, CA",
  "Thornton, CO", "Miramar, FL", "Pasadena, CA", "Mesquite, TX", "Olathe, KS",
  "Dayton, OH", "Charleston, SC", "Gainesville, FL", "Waco, TX", "West Valley City, UT",
  "Visalia, CA", "Tuscaloosa, AL", "Fargo, ND", "Topeka, KS", "Norman, OK",
  "Asheville, NC", "Wilmington, NC", "Boulder, CO", "Palm Bay, FL", "Lakeland, FL",
  "Camarillo, CA", "Fort Myers, FL", "Waynesville, NC", "Hilo, HI", "Fairbanks, AK",
];
